---
  all:
    vars:
      ansible_become: true
      ansible_become_method: sudo
      repo_host: 10.0.0.5
    children:
      openstack:
        hosts:
          node1:
            ansible_host: 10.0.0.21
          node2:
            ansible_host: 10.0.0.22
